drop table if exists t_dimdim_categoria cascade;
drop table if exists t_dimdim_lancamento cascade;
drop table if exists t_dimdim_usuario cascade;
drop table if exists t_dimdim_usuario cascade;

create table t_dimdim_categoria (
    data_criacao timestamp(6) not null,
    id_categoria bigint generated by default as identity,
    usuario_categoria_id bigint not null,
    nome_categoria varchar(100) not null,
    descricao varchar(255) not null,
    primary key (id_categoria)
);

create table t_dimdim_lancamento (
    valor_lancamento float(53) not null,
    categoria_lancamento_id bigint not null,
    data_lancamento timestamp(6) not null,
    id_lancamento bigint generated by default as identity,
    tipo_lancamento varchar(20) not null,
    primary key (id_lancamento)
);

create table t_dimdim_usuario (
    id_usuario bigint generated by default as identity,
    nome_usuario varchar(100) not null,
    email_usuario varchar(120) not null unique,
    senha_usuario varchar(255) not null,
    primary key (id_usuario)
);

alter table if exists t_dimdim_categoria 
    add constraint FKjx7m2xlj1t3kp2aay27il5yon 
    foreign key (usuario_categoria_id) 
    references t_dimdim_usuario;

alter table if exists t_dimdim_lancamento 
    add constraint FKpri6t3ofy2tyeieiyaiyovdcq 
    foreign key (categoria_lancamento_id) 
    references t_dimdim_categoria;