-- =============================================
-- USUÁRIOS
-- =============================================
INSERT INTO T_DIMDIM_USUARIO (NOME_USUARIO, EMAIL_USUARIO, SENHA_USUARIO)
VALUES ('Pedro Henrique', 'pedro@dimdim.com', '123456');

INSERT INTO T_DIMDIM_USUARIO (NOME_USUARIO, EMAIL_USUARIO, SENHA_USUARIO)
VALUES ('Ana Souza', 'ana@dimdim.com', 'senha123');

INSERT INTO T_DIMDIM_USUARIO (NOME_USUARIO, EMAIL_USUARIO, SENHA_USUARIO)
VALUES ('Carlos Lima', 'carlos@dimdim.com', 'abc123');

-- =============================================
-- CATEGORIAS
-- =============================================
INSERT INTO T_DIMDIM_CATEGORIA (NOME_CATEGORIA, DESCRICAO, USUARIO_CATEGORIA_ID, DATA_CRIACAO)
VALUES ('Alimentação', 'Gastos com restaurantes, mercados e delivery', 1, GETDATE());

INSERT INTO T_DIMDIM_CATEGORIA (NOME_CATEGORIA, DESCRICAO, USUARIO_CATEGORIA_ID, DATA_CRIACAO)
VALUES ('Transporte', 'Custos com combustível, ônibus, Uber, etc.', 1, GETDATE());

INSERT INTO T_DIMDIM_CATEGORIA (NOME_CATEGORIA, DESCRICAO, USUARIO_CATEGORIA_ID, DATA_CRIACAO)
VALUES ('Educação', 'Mensalidades e materiais de estudo', 2, GETDATE());

INSERT INTO T_DIMDIM_CATEGORIA (NOME_CATEGORIA, DESCRICAO, USUARIO_CATEGORIA_ID, DATA_CRIACAO)
VALUES ('Lazer', 'Cinema, viagens e entretenimento', 3, GETDATE());

-- =============================================
-- LANÇAMENTOS
-- =============================================
INSERT INTO T_DIMDIM_LANCAMENTO (VALOR_LANCAMENTO, DATA_LANCAMENTO, TIPO_LANCAMENTO, CATEGORIA_LANCAMENTO_ID)
VALUES (75.50, GETDATE(), 'SAIDA', 1);

INSERT INTO T_DIMDIM_LANCAMENTO (VALOR_LANCAMENTO, DATA_LANCAMENTO, TIPO_LANCAMENTO, CATEGORIA_LANCAMENTO_ID)
VALUES (300.00, GETDATE(), 'ENTRADA', 2);

INSERT INTO T_DIMDIM_LANCAMENTO (VALOR_LANCAMENTO, DATA_LANCAMENTO, TIPO_LANCAMENTO, CATEGORIA_LANCAMENTO_ID)
VALUES (1200.00, GETDATE(), 'ENTRADA', 3);

INSERT INTO T_DIMDIM_LANCAMENTO (VALOR_LANCAMENTO, DATA_LANCAMENTO, TIPO_LANCAMENTO, CATEGORIA_LANCAMENTO_ID)
VALUES (49.90, GETDATE(), 'SAIDA', 4);

INSERT INTO T_DIMDIM_LANCAMENTO (VALOR_LANCAMENTO, DATA_LANCAMENTO, TIPO_LANCAMENTO, CATEGORIA_LANCAMENTO_ID)
VALUES (20.00, GETDATE(), 'SAIDA', 1);
