-- Remove as tabelas apenas se existirem
IF OBJECT_ID('dbo.T_DIMDIM_LANCAMENTO', 'U') IS NOT NULL
DROP TABLE dbo.T_DIMDIM_LANCAMENTO;

IF OBJECT_ID('dbo.T_DIMDIM_CATEGORIA', 'U') IS NOT NULL
DROP TABLE dbo.T_DIMDIM_CATEGORIA;

IF OBJECT_ID('dbo.T_DIMDIM_USUARIO', 'U') IS NOT NULL
DROP TABLE dbo.T_DIMDIM_USUARIO;
