-- FK: Categoria → Usuário
IF OBJECT_ID('FK_T_DIMDIM_CATEGORIA_USUARIO', 'F') IS NOT NULL
ALTER TABLE dbo.T_DIMDIM_CATEGORIA DROP CONSTRAINT FK_T_DIMDIM_CATEGORIA_USUARIO;

ALTER TABLE dbo.T_DIMDIM_CATEGORIA
    ADD CONSTRAINT FK_T_DIMDIM_CATEGORIA_USUARIO
        FOREIGN KEY (USUARIO_CATEGORIA_ID)
            REFERENCES dbo.T_DIMDIM_USUARIO (ID_USUARIO)
            ON DELETE CASCADE;

-- FK: Lançamento → Categoria
IF OBJECT_ID('FK_T_DIMDIM_LANCAMENTO_CATEGORIA', 'F') IS NOT NULL
ALTER TABLE dbo.T_DIMDIM_LANCAMENTO DROP CONSTRAINT FK_T_DIMDIM_LANCAMENTO_CATEGORIA;

ALTER TABLE dbo.T_DIMDIM_LANCAMENTO
    ADD CONSTRAINT FK_T_DIMDIM_LANCAMENTO_CATEGORIA
        FOREIGN KEY (CATEGORIA_LANCAMENTO_ID)
            REFERENCES dbo.T_DIMDIM_CATEGORIA (ID_CATEGORIA)
            ON DELETE CASCADE;
