-- Popula usuários apenas se não existirem
IF NOT EXISTS (SELECT 1 FROM dbo.T_DIMDIM_USUARIO WHERE EMAIL_USUARIO = 'pedro@dimdim.com')
    INSERT INTO dbo.T_DIMDIM_USUARIO (NOME_USUARIO, EMAIL_USUARIO, SENHA_USUARIO)
    VALUES ('Pedro Henrique', 'pedro@dimdim.com', '123456');

IF NOT EXISTS (SELECT 1 FROM dbo.T_DIMDIM_USUARIO WHERE EMAIL_USUARIO = 'ana@dimdim.com')
    INSERT INTO dbo.T_DIMDIM_USUARIO (NOME_USUARIO, EMAIL_USUARIO, SENHA_USUARIO)
    VALUES ('Ana Souza', 'ana@dimdim.com', 'senha123');

IF NOT EXISTS (SELECT 1 FROM dbo.T_DIMDIM_USUARIO WHERE EMAIL_USUARIO = 'carlos@dimdim.com')
    INSERT INTO dbo.T_DIMDIM_USUARIO (NOME_USUARIO, EMAIL_USUARIO, SENHA_USUARIO)
    VALUES ('Carlos Lima', 'carlos@dimdim.com', 'abc123');

-- Popula categorias (vinculadas ao usuário)
DECLARE @idPedro BIGINT = (SELECT TOP 1 ID_USUARIO FROM dbo.T_DIMDIM_USUARIO WHERE EMAIL_USUARIO='pedro@dimdim.com');
DECLARE @idAna BIGINT = (SELECT TOP 1 ID_USUARIO FROM dbo.T_DIMDIM_USUARIO WHERE EMAIL_USUARIO='ana@dimdim.com');
DECLARE @idCarlos BIGINT = (SELECT TOP 1 ID_USUARIO FROM dbo.T_DIMDIM_USUARIO WHERE EMAIL_USUARIO='carlos@dimdim.com');

IF NOT EXISTS (SELECT 1 FROM dbo.T_DIMDIM_CATEGORIA WHERE NOME_CATEGORIA = 'Alimentação')
    INSERT INTO dbo.T_DIMDIM_CATEGORIA (NOME_CATEGORIA, DESCRICAO, USUARIO_CATEGORIA_ID, DATA_CRIACAO)
    VALUES ('Alimentação', 'Gastos com restaurantes, mercados e delivery', @idPedro, SYSDATETIME());

IF NOT EXISTS (SELECT 1 FROM dbo.T_DIMDIM_CATEGORIA WHERE NOME_CATEGORIA = 'Transporte')
    INSERT INTO dbo.T_DIMDIM_CATEGORIA (NOME_CATEGORIA, DESCRICAO, USUARIO_CATEGORIA_ID, DATA_CRIACAO)
    VALUES ('Transporte', 'Custos com combustível, ônibus, Uber, etc.', @idPedro, SYSDATETIME());

IF NOT EXISTS (SELECT 1 FROM dbo.T_DIMDIM_CATEGORIA WHERE NOME_CATEGORIA = 'Educação')
    INSERT INTO dbo.T_DIMDIM_CATEGORIA (NOME_CATEGORIA, DESCRICAO, USUARIO_CATEGORIA_ID, DATA_CRIACAO)
    VALUES ('Educação', 'Mensalidades e materiais de estudo', @idAna, SYSDATETIME());

IF NOT EXISTS (SELECT 1 FROM dbo.T_DIMDIM_CATEGORIA WHERE NOME_CATEGORIA = 'Lazer')
    INSERT INTO dbo.T_DIMDIM_CATEGORIA (NOME_CATEGORIA, DESCRICAO, USUARIO_CATEGORIA_ID, DATA_CRIACAO)
    VALUES ('Lazer', 'Cinema, viagens e entretenimento', @idCarlos, SYSDATETIME());

-- Popula lançamentos
DECLARE @idAlimentacao BIGINT = (SELECT TOP 1 ID_CATEGORIA FROM dbo.T_DIMDIM_CATEGORIA WHERE NOME_CATEGORIA='Alimentação');
DECLARE @idTransporte BIGINT  = (SELECT TOP 1 ID_CATEGORIA FROM dbo.T_DIMDIM_CATEGORIA WHERE NOME_CATEGORIA='Transporte');
DECLARE @idEducacao BIGINT    = (SELECT TOP 1 ID_CATEGORIA FROM dbo.T_DIMDIM_CATEGORIA WHERE NOME_CATEGORIA='Educação');
DECLARE @idLazer BIGINT       = (SELECT TOP 1 ID_CATEGORIA FROM dbo.T_DIMDIM_CATEGORIA WHERE NOME_CATEGORIA='Lazer');

IF NOT EXISTS (SELECT 1 FROM dbo.T_DIMDIM_LANCAMENTO WHERE VALOR_LANCAMENTO = 75.50)
    INSERT INTO dbo.T_DIMDIM_LANCAMENTO (VALOR_LANCAMENTO, DATA_LANCAMENTO, TIPO_LANCAMENTO, CATEGORIA_LANCAMENTO_ID)
    VALUES (75.50, SYSDATETIME(), 'SAIDA', @idAlimentacao);

IF NOT EXISTS (SELECT 1 FROM dbo.T_DIMDIM_LANCAMENTO WHERE VALOR_LANCAMENTO = 300.00)
    INSERT INTO dbo.T_DIMDIM_LANCAMENTO (VALOR_LANCAMENTO, DATA_LANCAMENTO, TIPO_LANCAMENTO, CATEGORIA_LANCAMENTO_ID)
    VALUES (300.00, SYSDATETIME(), 'ENTRADA', @idTransporte);

IF NOT EXISTS (SELECT 1 FROM dbo.T_DIMDIM_LANCAMENTO WHERE VALOR_LANCAMENTO = 1200.00)
    INSERT INTO dbo.T_DIMDIM_LANCAMENTO (VALOR_LANCAMENTO, DATA_LANCAMENTO, TIPO_LANCAMENTO, CATEGORIA_LANCAMENTO_ID)
    VALUES (1200.00, SYSDATETIME(), 'ENTRADA', @idEducacao);

IF NOT EXISTS (SELECT 1 FROM dbo.T_DIMDIM_LANCAMENTO WHERE VALOR_LANCAMENTO = 49.90)
    INSERT INTO dbo.T_DIMDIM_LANCAMENTO (VALOR_LANCAMENTO, DATA_LANCAMENTO, TIPO_LANCAMENTO, CATEGORIA_LANCAMENTO_ID)
    VALUES (49.90, SYSDATETIME(), 'SAIDA', @idLazer);
